### ISSUE TITLE
Is there any limitation on the number of cpus?

### ISSUE THREAD

**Issue by adwardlee** [hzwer/NIPS2017-LearningToRunACE#10]
Hi @hzwer ,

When I set the cores number to 48 in farmlist.py, there are only around 10 threads running. The farm frequently says " *** not found on rel(), might already be released". Do you know what is the problem? Thanks.

**Comment by hzwer** [comment]
I have no ideas.

**Comment by adwardlee** [comment]
OK, thanks anyway.
