### ISSUE TITLE
Link to weights broken

### ISSUE THREAD

**Issue by amir-abdi** [hzwer/NIPS2017-LearningToRunACE#12]
Hi,

Do you mind resharing the trained weights for the learning to run model?
The link below, provided in README.md, is broken:
https://drive.google.com/file/d/1aQuegutOwIJmKP7E7DbtZKYhYW9sEov4/view?usp=sharing

**Comment by hzwer** [comment]
I am very sorry that I did not see this issue in time.

**Comment by hzwer** [comment]
I fixed it.
