### ISSUE TITLE
A1C0 is equivalent to DDPG

### ISSUE THREAD

**Issue by huangh12** [hzwer/NIPS2017-LearningToRunACE#5]
Hello, 
      Thanks for sharing your work.
      I am just curious why you said A1C0 is equivalent to DDPG(or original actor-critic) in your arkiv paper. As we all know, DDPG has one actor and one critic. Isn't it be more appropriate to be regarded as A1C1?

**Comment by NewGod** [comment]
The "C0" means that we don't use any critic in the test section，because we only have one action each state, so we don'y need any critic in here. So in A1C0 we just train the model using DDPG, and then test the actor's performance. This is what we said "A1C0 is equivalent to DDPG".
