### ISSUE TITLE
Question about the trained parameters

### ISSUE THREAD

**Issue by adwardlee** [hzwer/NIPS2017-LearningToRunACE#9]
Hi @hzwer,

Is it reasonable that the ensemble of your trained 10 models report 22.41 mean reward in the testing? The released trained models are not your final models? Thanks.

**Comment by hzwer** [comment]
The released code is exactly based on my final code.
I set the number of obstacles as 3 for the writeup because it would be faster and easy to compare. Maybe the models I provided are these ones.
In the previous contest, I trained some models for more than 48 hours and combined them.

**Comment by adwardlee** [comment]
Thanks for your reply!
